"""Extract printable ASCII/UTF-16LE strings from EAW binaries and classify
threading/engine-relevant ones. Usage:
  python scripts/string_census.py "<game root>" "<output .md path>"
"""
import re, sys, os

BINARIES = [
    "corruption/StarWarsG.exe",
    "GameData/StarWarsG.exe",
    "corruption/PerceptionFunctionG.dll",
    "GameData/PerceptionFunctionG.dll",
    "corruption/swfoc.exe",
]

# (regex, category label) — applied to each extracted string
INTERESTING = [
    (r"[Tt]hread", "threading"),
    (r"[Mm]utex|CriticalSection|Semaphore|Event", "sync primitives"),
    (r"[Ll]ua", "lua"),
    (r"[Mm]ega", "megafile"),
    (r"[Pp]athfind", "pathfinding"),
    (r"[Pp]erception", "perception"),
    (r"[Jj]ob|[Ww]orker|[Tt]ask", "job/worker"),
    (r"[Aa]ffinity|[Cc]ore", "affinity"),
]

def extract_ascii(data, minlen=8):
    out = []
    for m in re.finditer(rb"[\x20-\x7e]{%d,}" % minlen, data):
        out.append((m.start(), m.group().decode()))
    return out

def extract_utf16le(data, minlen=8):
    out = []
    for m in re.finditer(rb"(?:[\x20-\x7e]\x00){%d,}" % minlen, data):
        out.append((m.start(), m.group().decode("utf-16le")))
    return out

def main():
    root = sys.argv[1].rstrip("\\/")
    out_path = sys.argv[2]
    lines = ["# String Census\n", "Auto-generated by scripts/string_census.py\n"]
    for rel in BINARIES:
        path = f"{root}/{rel}"
        if not os.path.exists(path):
            lines.append(f"\n## {rel}\n\nMISSING — skipped\n")
            continue
        with open(path, "rb") as f:
            data = f.read()
        strings = extract_ascii(data) + extract_utf16le(data)
        # unique, sorted by offset
        seen, uniq = set(), []
        for off, s in sorted(strings):
            if s not in seen:
                seen.add(s)
                uniq.append((off, s))
        hits = {}
        for off, s in uniq:
            for pat, cat in INTERESTING:
                if re.search(pat, s):
                    hits.setdefault(cat, []).append((off, s))
        lines.append(f"\n## {rel}\n\nTotal strings: {len(uniq)}\n")
        for cat in sorted(hits):
            lines.append(f"\n### {cat} ({len(hits[cat])} hits)\n")
            for off, s in hits[cat][:40]:
                lines.append(f"- `0x{off:08X}` {s}")
    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {out_path}")

if __name__ == "__main__":
    main()
